# Generated by Django 2.2.7 on 2021-03-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szafka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=300)),
                ('szerokosc', models.IntegerField(default=False)),
                ('wysokosc', models.IntegerField(default=False)),
                ('glebokosc', models.IntegerField(default=False)),
                ('plyta', models.IntegerField(default=False)),
            ],
        ),
    ]
