# Generated by Django 2.2.7 on 2021-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szafka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='szafka',
            name='ilosc_pulek',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='szafka',
            name='wzor_frontu',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AddField(
            model_name='szafka',
            name='wzor_sciany',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
