# Generated by Django 2.2.7 on 2021-03-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szafka', '0002_auto_20210307_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='szafka',
            old_name='ilosc_pulek',
            new_name='ilosc_polek',
        ),
    ]
