# Generated by Django 3.1.7 on 2021-03-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szafka', '0003_auto_20210307_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='szafka',
            name='glebokosc_wneki',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='szafka',
            name='ilosc_drzwi',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='szafka',
            name='narozna',
            field=models.BooleanField(default=False),
        ),
    ]
